\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		R1
		a1:m e1:m
		b1:7 b1:7 b1:7

		% los ninnos hebreos...
		e1:m e1:m e1:m e1:m
		d1 g1 g1
		a1:m e1:m
		b1:7 b1:7 b1:7

		% hosanna en el cielo...
		e1:m e1:m d1 g1
		a1:m b1:7 e1:m e1:m

		% portones...
		e1:m a1:m e1:m e1:m
		e1:m a1:m e1:m e1:m

		% va a entrar...
		g1 d1 g1 a1:m
		e1:m c1 b1:7 b1:7

		% hosanna en el cielo...
		e1:m e1:m d1 g1
		a1:m b1:7 e1:m e1:m
	}
